### ISSUE TITLE
Errors on every message.

### ISSUE THREAD

**Issue by KyeNormanGill** [Naval-Base/javelin#4]
Node version: 9.11.1
Javelin version: 0.2.0

Using a moderator account the regexes can't match an id on every message. 
Below is the stack trace along with other logs.
```
PS C:\Programming\TwitchBot> node .
Connecting
:tmi.twitch.tv 001 artfulsbots :Welcome, GLHF!
:tmi.twitch.tv 002 artfulsbots :Your host is tmi.twitch.tv
:tmi.twitch.tv 003 artfulsbots :This server is rather new
:tmi.twitch.tv 004 artfulsbots :-
:tmi.twitch.tv 375 artfulsbots :-
:tmi.twitch.tv 372 artfulsbots :You are in a maze of twisty passages, all alike.
:tmi.twitch.tv 376 artfulsbots :>

Ready! Woop!
:artfulsbots!artfulsbots@artfulsbots.tmi.twitch.tv JOIN #artful_au

:artfulsbots.tmi.twitch.tv 353 artfulsbots = #artful_au :artfulsbots
:artfulsbots.tmi.twitch.tv 366 artfulsbots #artful_au :End of /NAMES list

:artful_au!artful_au@artful_au.tmi.twitch.tv PRIVMSG #artful_au :!ping

C:\Programming\TwitchBot\node_modules\javelin\src\structs\Message.js:25
                this.id = data.match(/id=(.*?);/)[1];
                                                 ^

TypeError: Cannot read property '1' of null
    at new Message (C:\Programming\TwitchBot\node_modules\javelin\src\structs\Message.js:25:36)
    at WebSocket.onMessage (C:\Programming\TwitchBot\node_modules\javelin\src\client\websocket\WebSocket.js:69:32)
    at WebSocket.onMessage (C:\Programming\TwitchBot\node_modules\ws\lib\event-target.js:120:16)
    at WebSocket.emit (events.js:180:13)
    at Receiver.receiverOnMessage (C:\Programming\TwitchBot\node_modules\ws\lib\websocket.js:719:20)
    at Receiver.emit (events.js:180:13)
    at Receiver.dataMessage (C:\Programming\TwitchBot\node_modules\ws\lib\receiver.js:414:14)
    at Receiver.getData (C:\Programming\TwitchBot\node_modules\ws\lib\receiver.js:346:17)
    at Receiver.startLoop (C:\Programming\TwitchBot\node_modules\ws\lib\receiver.js:133:22)
    at Receiver._write (C:\Programming\TwitchBot\node_modules\ws\lib\receiver.js:69:10)
PS C:\Programming\TwitchBot>```

**Comment by iCrawl** [comment]
Potentially fixed in b68cd102d7f8e376d06f1148019408f1a5a872ad
